version: 0.0
# This is for a CodeDeploy deployment type 'ECS', but we're leveraging its hooks for EKS
# Resource property values are placeholders as CodeDeploy doesn't directly manage EKS resources
# Instead, we use a script in the hooks to run kubectl commands.
Resources:
  - myApp:
      Type: AWS::ECS::Service # Placeholder, CodeDeploy doesn't have an EKS resource type
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:913524942450:task-definition/dummy:1"
        LoadBalancerInfo:
          ContainerName: "brain-tasks-container" # Must match container name in imagedefinitions.json
          ContainerPort: 80 # Must match container port in imagedefinitions.json
Hooks:
  AfterInstall:
    - location: scripts/deploy_to_eks.sh
      timeout: 300
      runas: root
